# 1. DATA INPUT
data:
  filepath: "data/2023-2025-Aurino-Caminata-SSC-Q.csv"
  datetime_col: "datetime"
  stressor_col: "ssc"
  # Optional, for the SSC plot
  discharge_col: "q" 
  
  # (Optional) Uncomment and specify the format if auto-detection fails.
  datetime_format: null
  
  # (Optional) Replaces all 0 values in the stressor column.
  # Set to null to disable.
  replace_zeros_with: 0.025
  
  read_csv_options:
    comment: '#'
    #delimiter: ';'
    

# 2. MODEL SELECTION
model:
  # Python path to the model file and class
  module: "models.sev"
  class: "SEVModel"
  
  # Parameters to pass to the model's __init__
  params:
    group: 1

# 3. ANALYSIS PARAMETERS
analysis:
  # The response levels to evaluate
  response_targets: [4, 5, 6, 7, 8, 9,]
  
  # Maximum duration to scan (in hours)
  max_duration_hours: null 
  
  # Optional baseline filter
  baseline_percentile: null
  
  # Optional data smoothing (moving average)
  # Set to 1 disable smoothing
  moving_avg_window: 1 #in time steps
  
  # For the static UCUT comparison
  static_threshold: null
  


# 4. OUTPUT & PLOTTING
plotting:
  colormap: "binary"
  stressor_label: "SSC (mg/L)" # For plot axes
  response_label: "SEV Level"  # For plot axes
  output_dir: "results/"